// src/control-plane/reporter.test.ts
import { describe, it, expect, vi } from 'vitest';
import { formatReport, postReport } from './reporter.js';
import type { RunState } from '../types.js';

function makeRunState(overrides?: Partial<RunState>): RunState {
  return {
    issueNumber: 42,
    title: 'Add dark mode support',
    phase: 'report',
    variant: 'feature',
    phaseCompletions: {
      detect: true,
      classify: true,
      implement: true,
      review: true,
    },
    checkpoints: [],
    cost: 3.14,
    perRunBudget: 10,
    fixAttempts: [
      { phase: 'implement', attempt: 1, errorHash: 'abc123' },
    ],
    errorHashes: {},
    startedAt: '2026-03-19T10:00:00Z',
    updatedAt: '2026-03-19T10:30:00Z',
    ...overrides,
  };
}

describe('formatReport', () => {
  it('produces a markdown report with issue number in heading', () => {
    const run = makeRunState();
    const report = formatReport(run, 'complete');
    expect(report).toContain('## Auto-Claude Report: #42');
  });

  it('includes outcome in the report', () => {
    const run = makeRunState();
    const report = formatReport(run, 'complete');
    expect(report).toContain('**Outcome:** complete');
  });

  it('includes pipeline variant', () => {
    const run = makeRunState();
    const report = formatReport(run, 'complete');
    expect(report).toContain('**Pipeline:** feature');
  });

  it('includes cost formatted to 2 decimal places', () => {
    const run = makeRunState({ cost: 3.14159 });
    const report = formatReport(run, 'complete');
    expect(report).toContain('**Cost:** $3.14');
  });

  it('includes completed phases', () => {
    const run = makeRunState();
    const report = formatReport(run, 'complete');
    expect(report).toContain('**Phases completed:**');
    expect(report).toContain('detect');
    expect(report).toContain('classify');
    expect(report).toContain('implement');
    expect(report).toContain('review');
  });

  it('shows "none" when no phases completed', () => {
    const run = makeRunState({ phaseCompletions: {} });
    const report = formatReport(run, 'stuck');
    expect(report).toContain('**Phases completed:** none');
  });

  it('includes fix attempt count', () => {
    const run = makeRunState();
    const report = formatReport(run, 'complete');
    expect(report).toContain('**Fix attempts:** 1');
  });

  it('includes generated-by footer', () => {
    const run = makeRunState();
    const report = formatReport(run, 'complete');
    expect(report).toContain('*Generated by Auto-Claude*');
  });

  it('includes hr separator', () => {
    const run = makeRunState();
    const report = formatReport(run, 'complete');
    expect(report).toContain('---');
  });

  it('handles different outcomes', () => {
    const run = makeRunState();
    expect(formatReport(run, 'stuck')).toContain('**Outcome:** stuck');
    expect(formatReport(run, 'escalated')).toContain('**Outcome:** escalated');
  });
});

describe('postReport', () => {
  it('calls octokit.issues.createComment with correct arguments', async () => {
    const createComment = vi.fn().mockResolvedValue({});
    const octokit = {
      issues: { createComment },
    } as unknown as Parameters<typeof postReport>[0];

    const result = await postReport(octokit, 'myorg', 'myrepo', 42, '## Report');

    expect(result.ok).toBe(true);
    expect(createComment).toHaveBeenCalledWith({
      owner: 'myorg',
      repo: 'myrepo',
      issue_number: 42,
      body: '## Report',
    });
  });

  it('returns ok(undefined) on success', async () => {
    const createComment = vi.fn().mockResolvedValue({});
    const octokit = {
      issues: { createComment },
    } as unknown as Parameters<typeof postReport>[0];

    const result = await postReport(octokit, 'myorg', 'myrepo', 1, 'body');

    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value).toBeUndefined();
    }
  });

  it('returns err when octokit throws', async () => {
    const createComment = vi.fn().mockRejectedValue(new Error('API rate limit exceeded'));
    const octokit = {
      issues: { createComment },
    } as unknown as Parameters<typeof postReport>[0];

    const result = await postReport(octokit, 'myorg', 'myrepo', 1, 'body');

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.message).toBe('API rate limit exceeded');
    }
  });

  it('wraps non-Error throws in an Error', async () => {
    const createComment = vi.fn().mockRejectedValue('string error');
    const octokit = {
      issues: { createComment },
    } as unknown as Parameters<typeof postReport>[0];

    const result = await postReport(octokit, 'myorg', 'myrepo', 1, 'body');

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error).toBeInstanceOf(Error);
    }
  });
});
