// src/control-plane/release.ts
import { readResults } from './results.js';
import type { ResultsRecord } from '../types.js';
import type { Octokit } from '@octokit/rest';

export interface ReleaseNotes {
  title: string;
  body: string;
  issueCount: number;
  totalCost: number;
}

export type ReleaseProposalResult =
  | {
      status: 'success';
      prNumber: number;
      prUrl: string;
      issueCount: number;
      totalCost: number;
      title: string;
      body: string;
    }
  | {
      status: 'no-completed-work';
      issueCount: 0;
      totalCost: 0;
      title: string;
      body: string;
    }
  | {
      status: 'single-trunk-not-applicable';
      issueCount: number;
      totalCost: number;
      title: string;
      body: string;
    };

export async function aggregateReleaseNotes(
  stateDir?: string,
  since?: string,
): Promise<ReleaseNotes> {
  const results = await readResults(stateDir);
  const completed = results.filter((r: ResultsRecord) => {
    if (r.outcome !== 'complete') return false;
    if (since && r.completedAt < since) return false;
    return true;
  });

  const issueList = completed
    .map(
      (r: ResultsRecord) =>
        `- #${r.issueNumber}: ${r.variant} pipeline, $${r.totalCost.toFixed(2)}`,
    )
    .join('\n');

  const totalCost = completed.reduce((sum: number, r: ResultsRecord) => sum + r.totalCost, 0);

  return {
    title: `Release: ${completed.length} issue${completed.length === 1 ? '' : 's'}`,
    body: [
      '## Release Notes',
      '',
      `**Issues completed:** ${completed.length}`,
      `**Total cost:** $${totalCost.toFixed(2)}`,
      '',
      '### Issues',
      issueList || '_No completed issues since last release._',
      '',
      '---',
      '_Generated by Auto-Claude_',
    ].join('\n'),
    issueCount: completed.length,
    totalCost,
  };
}

export async function createReleaseProposal(
  octokit: Octokit,
  owner: string,
  repo: string,
  stagingBranch: string,
  productionBranch: string,
  stateDir?: string,
): Promise<ReleaseProposalResult> {
  const notes = await aggregateReleaseNotes(stateDir);
  if (notes.issueCount === 0) {
    return {
      status: 'no-completed-work',
      issueCount: 0,
      totalCost: 0,
      title: notes.title,
      body: notes.body,
    };
  }

  if (stagingBranch === productionBranch) {
    return {
      status: 'single-trunk-not-applicable',
      issueCount: notes.issueCount,
      totalCost: notes.totalCost,
      title: notes.title,
      body: notes.body,
    };
  }

  const pr = await octokit.pulls.create({
    owner,
    repo,
    head: stagingBranch,
    base: productionBranch,
    title: notes.title,
    body: notes.body,
  });

  return {
    status: 'success',
    prNumber: pr.data.number,
    prUrl: pr.data.html_url,
    issueCount: notes.issueCount,
    totalCost: notes.totalCost,
    title: notes.title,
    body: notes.body,
  };
}
