// src/control-plane/release.ts
import { readResults } from './results.js';
import type { ResultsRecord } from '../types.js';

export interface ReleaseNotes {
  title: string;
  body: string;
  issueCount: number;
  totalCost: number;
}

export async function aggregateReleaseNotes(
  stateDir?: string,
  since?: string,
): Promise<ReleaseNotes> {
  const results = await readResults(stateDir);
  const completed = results.filter((r: ResultsRecord) => {
    if (r.outcome !== 'complete') return false;
    if (since && r.completedAt < since) return false;
    return true;
  });

  const issueList = completed
    .map(
      (r: ResultsRecord) =>
        `- #${r.issueNumber}: ${r.variant} pipeline, $${r.totalCost.toFixed(2)}`,
    )
    .join('\n');

  const totalCost = completed.reduce((sum: number, r: ResultsRecord) => sum + r.totalCost, 0);

  return {
    title: `Release: ${completed.length} issue${completed.length === 1 ? '' : 's'}`,
    body: [
      '## Release Notes',
      '',
      `**Issues completed:** ${completed.length}`,
      `**Total cost:** $${totalCost.toFixed(2)}`,
      '',
      '### Issues',
      issueList || '_No completed issues since last release._',
      '',
      '---',
      '_Generated by Auto-Claude_',
    ].join('\n'),
    issueCount: completed.length,
    totalCost,
  };
}
