// src/control-plane/reporter.ts
import type { Octokit } from '@octokit/rest';
import type { RunState } from '../types.js';
import { ok, err, type Result } from '../lib/result.js';

export function formatReport(run: RunState, outcome: string): string {
  const phases = Object.entries(run.phaseCompletions)
    .filter(([, v]) => v)
    .map(([k]) => k);

  return [
    `## Auto-Claude Report: #${run.issueNumber}`,
    '',
    `**Outcome:** ${outcome}`,
    `**Pipeline:** ${run.variant}`,
    `**Cost:** $${run.cost.toFixed(2)}`,
    `**Phases completed:** ${phases.join(', ') || 'none'}`,
    `**Fix attempts:** ${run.fixAttempts.length}`,
    '',
    `---`,
    `*Generated by Auto-Claude*`,
  ].join('\n');
}

export async function postReport(
  octokit: Octokit,
  owner: string,
  repo: string,
  issueNumber: number,
  body: string,
): Promise<Result<void>> {
  try {
    await octokit.issues.createComment({
      owner,
      repo,
      issue_number: issueNumber,
      body,
    });
    return ok(undefined);
  } catch (e) {
    return err(e instanceof Error ? e : new Error(String(e)));
  }
}
