import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Db } from "./db.js";

/**
 * Apply committed migration SQL (generated by drizzle-kit) on startup.
 * Idempotent: tables use `CREATE TABLE` from drizzle-kit; we run each statement
 * and ignore "already exists" so repeated startup is safe. Migrations live next
 * to this module in ./migrations/*.sql, applied in lexical order.
 */
export function migrate(db: Db): void {
  const here = dirname(fileURLToPath(import.meta.url));
  const migDir = join(here, "migrations");
  const files = readdirSync(migDir)
    .filter((f) => f.endsWith(".sql"))
    .sort();

  const client = db.$client;
  for (const f of files) {
    const raw = readFileSync(join(migDir, f), "utf8");
    // drizzle-kit separates statements with a "--> statement-breakpoint" marker.
    const statements = raw
      .split(/-->\s*statement-breakpoint/g)
      .map((s) => s.trim())
      .filter((s) => s.length > 0);
    for (const stmt of statements) {
      try {
        client.exec(stmt);
      } catch (e) {
        // Idempotent startup: tolerate re-applying an already-applied migration
        // (CREATE TABLE -> "already exists"; ALTER TABLE ADD COLUMN ->
        // "duplicate column name").
        const msg = (e as Error).message ?? "";
        if (/already exists/i.test(msg) || /duplicate column name/i.test(msg)) continue;
        throw e;
      }
    }
  }
}
