import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { migrate as pgMigrate } from "drizzle-orm/postgres-js/migrator";
import type { PostgresJsDatabase } from "drizzle-orm/postgres-js";

import type * as schema from "./schema.js";

const here = dirname(fileURLToPath(import.meta.url));
const defaultMigrationsFolder = resolve(here, "../drizzle");

/**
 * Apply the committed Postgres migrations (generated by drizzle-kit) for the
 * dedicated `decision_index` schema. Migration state is tracked in
 * `decision_index.__drizzle_migrations` (migrationsSchema), so re-running on
 * startup is a no-op once applied — no error-swallowing like the old sqlite
 * migrator. The generated 0000 baseline creates the schema idempotently
 * (`CREATE SCHEMA IF NOT EXISTS`), which is safe alongside the migrator's own
 * `CREATE SCHEMA IF NOT EXISTS <migrationsSchema>` pre-step.
 */
export async function migrate(
  db: PostgresJsDatabase<typeof schema>,
  migrationsFolder: string = defaultMigrationsFolder,
): Promise<void> {
  await pgMigrate(db, {
    migrationsFolder,
    migrationsSchema: "decision_index",
  });
}
