export function buildL0Vision(projectName: string, visionStatement: string): string {
  return `# L0 Vision — ${projectName}

## Purpose

${visionStatement}

## Created

${new Date().toISOString().split('T')[0]}
`;
}

export function buildAgentsMd(): string {
  return `# AGENTS.md

This file contains rules and guidelines for AI agents working in this repository.

## Getting Started

Read CLAUDE.md for Claude Code-specific instructions.
`;
}

export function buildClaudeMd(): string {
  return `@AGENTS.md
`;
}

export function buildTraceabilityYml(projectName: string): string {
  return `# .specify/traceability.yml
# Auto-generated by runforge command center
# Project: ${projectName}

specs: []
`;
}

export function buildWorkflowYml(): string {
  return `# .runforge/workflow.yml
# Workflow gate configuration — managed by runforge dashboard

extends: default
`;
}
